// @letissier/design-system 0.1.0 · tokens.js · sha256-6ed2b8b9cdf982df · vendored by scripts/sync.mjs; change the design-system repo, not this copy
// GENERATED by build/build.mjs from tokens/*.tokens.json — do not edit.
// design-system 0.1.0 · change a token in tokens/, then run `npm run build`.

/** The modes of each axis; the first is the default. */
export const modes = {
  "theme": [
    "dark",
    "light"
  ],
  "density": [
    "regular",
    "compact",
    "touch"
  ]
};

/** Raw palette, by CIELAB lightness. Prefer the roles in `color`. */
export const palette = {
  "neutral": {
    "0": "#000000",
    "5": "#101012",
    "6": "#141415",
    "10": "#1c1c1e",
    "13": "#212124",
    "17": "#2a2a2e",
    "19": "#2e2e33",
    "21": "#323238",
    "26": "#3c3c44",
    "32": "#4a4a52",
    "39": "#5c5c66",
    "46": "#6d6c76",
    "59": "#8c8c96",
    "71": "#adadb7",
    "79": "#c4c4cc",
    "84": "#d2d2d8",
    "86": "#d6d6dc",
    "90": "#e2e2e7",
    "94": "#ececef",
    "97": "#f5f5f7",
    "99": "#fbfbfc",
    "100": "#ffffff"
  },
  "cyan": {
    "36": "#015b7e",
    "42": "#036a91",
    "74": "#39c2ff",
    "80": "#78d1ff"
  },
  "amber": {
    "40": "#835503",
    "56": "#b8790b",
    "78": "#ffb347"
  },
  "red": {
    "40": "#be0920",
    "59": "#ff4d4d",
    "64": "#fe6c67"
  },
  "green": {
    "40": "#026d3a",
    "76": "#33d67e"
  },
  "alpha": {
    "white-6": "#ffffff0f",
    "white-10": "#ffffff1a",
    "black-6": "#0000000f",
    "black-10": "#0000001a",
    "black-20": "#00000033",
    "black-30": "#0000004d",
    "black-40": "#00000066",
    "black-45": "#00000073",
    "black-55": "#0000008c",
    "cyan-74-16": "#39c2ff29",
    "cyan-42-10": "#036a911a",
    "amber-78-14": "#ffb34724",
    "amber-56-16": "#b8790b29",
    "red-59-14": "#ff4d4d24",
    "red-40-10": "#be09201a",
    "green-76-12": "#33d67e1f",
    "green-40-10": "#026d3a1a"
  }
};

/** Colour roles per theme, resolved to hex. */
export const color = {
  "dark": {
    "surface": {
      "ground": "#141415",
      "panel": "#1c1c1e",
      "inset": "#212124",
      "raised": "#2a2a2e",
      "raised-hover": "#323238",
      "overlay": "#212124",
      "canvas": "#101012"
    },
    "ink": {
      "primary": "#d2d2d8",
      "secondary": "#adadb7",
      "tertiary": "#8c8c96",
      "disabled": "#5c5c66",
      "inverse": "#141415",
      "on-canvas": "#d2d2d8"
    },
    "line": {
      "subtle": "#2e2e33",
      "strong": "#3c3c44",
      "control": "#6d6c76"
    },
    "accent": {
      "default": "#39c2ff",
      "hover": "#78d1ff",
      "ink": "#39c2ff",
      "on": "#101012",
      "soft": "#39c2ff29"
    },
    "focus": "#39c2ff",
    "ok": {
      "default": "#33d67e",
      "ink": "#33d67e",
      "on": "#101012",
      "soft": "#33d67e1f"
    },
    "warn": {
      "default": "#ffb347",
      "ink": "#ffb347",
      "on": "#101012",
      "soft": "#ffb34724"
    },
    "bad": {
      "default": "#ff4d4d",
      "ink": "#fe6c67",
      "on": "#101012",
      "soft": "#ff4d4d24"
    },
    "wash": {
      "hover": "#ffffff0f",
      "pressed": "#ffffff1a"
    },
    "veil": "#0000008c"
  },
  "light": {
    "surface": {
      "ground": "#ececef",
      "panel": "#f5f5f7",
      "inset": "#e2e2e7",
      "raised": "#fbfbfc",
      "raised-hover": "#d6d6dc",
      "overlay": "#ffffff",
      "canvas": "#101012"
    },
    "ink": {
      "primary": "#1c1c1e",
      "secondary": "#3c3c44",
      "tertiary": "#5c5c66",
      "disabled": "#8c8c96",
      "inverse": "#f5f5f7",
      "on-canvas": "#d2d2d8"
    },
    "line": {
      "subtle": "#c4c4cc",
      "strong": "#8c8c96",
      "control": "#6d6c76"
    },
    "accent": {
      "default": "#036a91",
      "hover": "#015b7e",
      "ink": "#015b7e",
      "on": "#ffffff",
      "soft": "#036a911a"
    },
    "focus": "#036a91",
    "ok": {
      "default": "#026d3a",
      "ink": "#026d3a",
      "on": "#ffffff",
      "soft": "#026d3a1a"
    },
    "warn": {
      "default": "#b8790b",
      "ink": "#835503",
      "on": "#101012",
      "soft": "#b8790b29"
    },
    "bad": {
      "default": "#be0920",
      "ink": "#be0920",
      "on": "#ffffff",
      "soft": "#be09201a"
    },
    "wash": {
      "hover": "#0000000f",
      "pressed": "#0000001a"
    },
    "veil": "#00000066"
  }
};

/** Box shadows per theme, as CSS. */
export const elevation = {
  "dark": {
    "menu": "0px 8px 24px 0px #00000073",
    "modal": "0px 18px 50px 0px #0000008c"
  },
  "light": {
    "menu": "0px 8px 24px 0px #00000033",
    "modal": "0px 18px 50px 0px #0000004d"
  }
};

/** Font families (as lists and as CSS stacks) and weights. */
export const font = {
  "family": {
    "sans": [
      "IBM Plex Sans",
      "system-ui",
      "-apple-system",
      "BlinkMacSystemFont",
      "Segoe UI",
      "Roboto",
      "Helvetica Neue",
      "Arial",
      "sans-serif"
    ],
    "mono": [
      "IBM Plex Mono",
      "ui-monospace",
      "SF Mono",
      "SFMono-Regular",
      "Menlo",
      "Consolas",
      "monospace"
    ],
    "display": [
      "Archivo",
      "IBM Plex Sans",
      "system-ui",
      "sans-serif"
    ]
  },
  "stack": {
    "sans": "'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    "mono": "'IBM Plex Mono', ui-monospace, 'SF Mono', SFMono-Regular, Menlo, Consolas, monospace",
    "display": "Archivo, 'IBM Plex Sans', system-ui, sans-serif"
  },
  "weight": {
    "regular": 400,
    "medium": 500,
    "semibold": 600,
    "bold": 700
  }
};

/** Text styles per density: size in px, leading as a multiple, tracking in em. */
export const text = {
  "regular": {
    "label": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 11,
      "weight": 500,
      "leading": 1.2,
      "tracking": "0.08em",
      "case": "uppercase"
    },
    "caption": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 12,
      "weight": 400,
      "leading": 1.35,
      "tracking": "0em",
      "case": "none"
    },
    "body": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 13,
      "weight": 400,
      "leading": 1.45,
      "tracking": "0em",
      "case": "none"
    },
    "control": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 13,
      "weight": 500,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "prose": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 14,
      "weight": 400,
      "leading": 1.55,
      "tracking": "0em",
      "case": "none"
    },
    "title": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 15,
      "weight": 600,
      "leading": 1.3,
      "tracking": "0em",
      "case": "none"
    },
    "heading": {
      "family": [
        "Archivo",
        "IBM Plex Sans",
        "system-ui",
        "sans-serif"
      ],
      "size": 20,
      "weight": 600,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "display": {
      "family": [
        "Archivo",
        "IBM Plex Sans",
        "system-ui",
        "sans-serif"
      ],
      "size": 32,
      "weight": 700,
      "leading": 1.1,
      "tracking": "-0.01em",
      "case": "none"
    },
    "numeric": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 13,
      "weight": 400,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "readout": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 22,
      "weight": 500,
      "leading": 1,
      "tracking": "0em",
      "case": "none"
    },
    "code": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 13,
      "weight": 400,
      "leading": 1.5,
      "tracking": "0em",
      "case": "none"
    }
  },
  "compact": {
    "label": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 11,
      "weight": 500,
      "leading": 1.2,
      "tracking": "0.08em",
      "case": "uppercase"
    },
    "caption": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 11,
      "weight": 400,
      "leading": 1.35,
      "tracking": "0em",
      "case": "none"
    },
    "body": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 12,
      "weight": 400,
      "leading": 1.45,
      "tracking": "0em",
      "case": "none"
    },
    "control": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 12,
      "weight": 500,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "prose": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 12,
      "weight": 400,
      "leading": 1.55,
      "tracking": "0em",
      "case": "none"
    },
    "title": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 13,
      "weight": 600,
      "leading": 1.3,
      "tracking": "0em",
      "case": "none"
    },
    "heading": {
      "family": [
        "Archivo",
        "IBM Plex Sans",
        "system-ui",
        "sans-serif"
      ],
      "size": 18,
      "weight": 600,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "display": {
      "family": [
        "Archivo",
        "IBM Plex Sans",
        "system-ui",
        "sans-serif"
      ],
      "size": 28,
      "weight": 700,
      "leading": 1.1,
      "tracking": "-0.01em",
      "case": "none"
    },
    "numeric": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 12,
      "weight": 400,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "readout": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 22,
      "weight": 500,
      "leading": 1,
      "tracking": "0em",
      "case": "none"
    },
    "code": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 12,
      "weight": 400,
      "leading": 1.5,
      "tracking": "0em",
      "case": "none"
    }
  },
  "touch": {
    "label": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 12,
      "weight": 500,
      "leading": 1.2,
      "tracking": "0.08em",
      "case": "uppercase"
    },
    "caption": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 13,
      "weight": 400,
      "leading": 1.35,
      "tracking": "0em",
      "case": "none"
    },
    "body": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 15,
      "weight": 400,
      "leading": 1.45,
      "tracking": "0em",
      "case": "none"
    },
    "control": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 15,
      "weight": 500,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "prose": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 16,
      "weight": 400,
      "leading": 1.55,
      "tracking": "0em",
      "case": "none"
    },
    "title": {
      "family": [
        "IBM Plex Sans",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif"
      ],
      "size": 17,
      "weight": 600,
      "leading": 1.3,
      "tracking": "0em",
      "case": "none"
    },
    "heading": {
      "family": [
        "Archivo",
        "IBM Plex Sans",
        "system-ui",
        "sans-serif"
      ],
      "size": 24,
      "weight": 600,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "display": {
      "family": [
        "Archivo",
        "IBM Plex Sans",
        "system-ui",
        "sans-serif"
      ],
      "size": 40,
      "weight": 700,
      "leading": 1.1,
      "tracking": "-0.01em",
      "case": "none"
    },
    "numeric": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 15,
      "weight": 400,
      "leading": 1.2,
      "tracking": "0em",
      "case": "none"
    },
    "readout": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 28,
      "weight": 500,
      "leading": 1,
      "tracking": "0em",
      "case": "none"
    },
    "code": {
      "family": [
        "IBM Plex Mono",
        "ui-monospace",
        "SF Mono",
        "SFMono-Regular",
        "Menlo",
        "Consolas",
        "monospace"
      ],
      "size": 14,
      "weight": 400,
      "leading": 1.5,
      "tracking": "0em",
      "case": "none"
    }
  }
};

/** The 4px spacing grid, in px. */
export const space = {
  "0": 0,
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 20,
  "6": 24,
  "8": 32,
  "10": 40,
  "12": 48,
  "16": 64,
  "hairline": 1,
  "half": 2
};

/** Control geometry per density, in px. */
export const size = {
  "regular": {
    "control": 32,
    "control-sm": 24,
    "control-padding": 12,
    "target": 24,
    "icon": 16,
    "row": 32,
    "bar": 48,
    "focus-ring": 2
  },
  "compact": {
    "control": 26,
    "control-sm": 20,
    "control-padding": 8,
    "target": 24,
    "icon": 14,
    "row": 24,
    "bar": 40,
    "focus-ring": 2
  },
  "touch": {
    "control": 44,
    "control-sm": 32,
    "control-padding": 16,
    "target": 44,
    "icon": 20,
    "row": 44,
    "bar": 56,
    "focus-ring": 2
  }
};

/** Corner radii per density, in px. */
export const radius = {
  "regular": {
    "none": 0,
    "control": 4,
    "panel": 6,
    "overlay": 8,
    "pill": 999
  },
  "compact": {
    "none": 0,
    "control": 3,
    "panel": 4,
    "overlay": 6,
    "pill": 999
  },
  "touch": {
    "none": 0,
    "control": 6,
    "panel": 8,
    "overlay": 12,
    "pill": 999
  }
};

/** Animation durations in ms. Honour prefers-reduced-motion yourself when you animate in JS. */
export const duration = {
  "instant": 70,
  "fast": 120,
  "base": 160,
  "slow": 240
};

/** Cubic-bézier control points. */
export const easing = {
  "standard": [
    0.2,
    0,
    0,
    1
  ],
  "enter": [
    0,
    0,
    0.2,
    1
  ],
  "exit": [
    0.4,
    0,
    1,
    1
  ]
};

/** Behavioural timers in ms: long-press, the armed window, a notice. */
export const timing = {
  "hold": 500,
  "arm": 3000,
  "notice": 4000
};

/** z-index values. */
export const layer = {
  "sticky": 10,
  "modal": 200,
  "popover": 300,
  "toast": 400,
  "tooltip": 500
};

/** Token id → CSS custom property name. */
export const cssVar = {
  "palette.neutral.0": "--ds-neutral-0",
  "palette.neutral.5": "--ds-neutral-5",
  "palette.neutral.6": "--ds-neutral-6",
  "palette.neutral.10": "--ds-neutral-10",
  "palette.neutral.13": "--ds-neutral-13",
  "palette.neutral.17": "--ds-neutral-17",
  "palette.neutral.19": "--ds-neutral-19",
  "palette.neutral.21": "--ds-neutral-21",
  "palette.neutral.26": "--ds-neutral-26",
  "palette.neutral.32": "--ds-neutral-32",
  "palette.neutral.39": "--ds-neutral-39",
  "palette.neutral.46": "--ds-neutral-46",
  "palette.neutral.59": "--ds-neutral-59",
  "palette.neutral.71": "--ds-neutral-71",
  "palette.neutral.79": "--ds-neutral-79",
  "palette.neutral.84": "--ds-neutral-84",
  "palette.neutral.86": "--ds-neutral-86",
  "palette.neutral.90": "--ds-neutral-90",
  "palette.neutral.94": "--ds-neutral-94",
  "palette.neutral.97": "--ds-neutral-97",
  "palette.neutral.99": "--ds-neutral-99",
  "palette.neutral.100": "--ds-neutral-100",
  "palette.cyan.36": "--ds-cyan-36",
  "palette.cyan.42": "--ds-cyan-42",
  "palette.cyan.74": "--ds-cyan-74",
  "palette.cyan.80": "--ds-cyan-80",
  "palette.amber.40": "--ds-amber-40",
  "palette.amber.56": "--ds-amber-56",
  "palette.amber.78": "--ds-amber-78",
  "palette.red.40": "--ds-red-40",
  "palette.red.59": "--ds-red-59",
  "palette.red.64": "--ds-red-64",
  "palette.green.40": "--ds-green-40",
  "palette.green.76": "--ds-green-76",
  "palette.alpha.white-6": "--ds-alpha-white-6",
  "palette.alpha.white-10": "--ds-alpha-white-10",
  "palette.alpha.black-6": "--ds-alpha-black-6",
  "palette.alpha.black-10": "--ds-alpha-black-10",
  "palette.alpha.black-20": "--ds-alpha-black-20",
  "palette.alpha.black-30": "--ds-alpha-black-30",
  "palette.alpha.black-40": "--ds-alpha-black-40",
  "palette.alpha.black-45": "--ds-alpha-black-45",
  "palette.alpha.black-55": "--ds-alpha-black-55",
  "palette.alpha.cyan-74-16": "--ds-alpha-cyan-74-16",
  "palette.alpha.cyan-42-10": "--ds-alpha-cyan-42-10",
  "palette.alpha.amber-78-14": "--ds-alpha-amber-78-14",
  "palette.alpha.amber-56-16": "--ds-alpha-amber-56-16",
  "palette.alpha.red-59-14": "--ds-alpha-red-59-14",
  "palette.alpha.red-40-10": "--ds-alpha-red-40-10",
  "palette.alpha.green-76-12": "--ds-alpha-green-76-12",
  "palette.alpha.green-40-10": "--ds-alpha-green-40-10",
  "font.family.sans": "--ds-font-sans",
  "font.family.mono": "--ds-font-mono",
  "font.family.display": "--ds-font-display",
  "font.weight.regular": "--ds-weight-regular",
  "font.weight.medium": "--ds-weight-medium",
  "font.weight.semibold": "--ds-weight-semibold",
  "font.weight.bold": "--ds-weight-bold",
  "text.label.family": "--ds-text-label-family",
  "text.label.size": "--ds-text-label-size",
  "text.label.weight": "--ds-text-label-weight",
  "text.label.leading": "--ds-text-label-leading",
  "text.label.tracking": "--ds-text-label-tracking",
  "text.label.case": "--ds-text-label-case",
  "text.caption.family": "--ds-text-caption-family",
  "text.caption.size": "--ds-text-caption-size",
  "text.caption.weight": "--ds-text-caption-weight",
  "text.caption.leading": "--ds-text-caption-leading",
  "text.caption.tracking": "--ds-text-caption-tracking",
  "text.caption.case": "--ds-text-caption-case",
  "text.body.family": "--ds-text-body-family",
  "text.body.size": "--ds-text-body-size",
  "text.body.weight": "--ds-text-body-weight",
  "text.body.leading": "--ds-text-body-leading",
  "text.body.tracking": "--ds-text-body-tracking",
  "text.body.case": "--ds-text-body-case",
  "text.control.family": "--ds-text-control-family",
  "text.control.size": "--ds-text-control-size",
  "text.control.weight": "--ds-text-control-weight",
  "text.control.leading": "--ds-text-control-leading",
  "text.control.tracking": "--ds-text-control-tracking",
  "text.control.case": "--ds-text-control-case",
  "text.prose.family": "--ds-text-prose-family",
  "text.prose.size": "--ds-text-prose-size",
  "text.prose.weight": "--ds-text-prose-weight",
  "text.prose.leading": "--ds-text-prose-leading",
  "text.prose.tracking": "--ds-text-prose-tracking",
  "text.prose.case": "--ds-text-prose-case",
  "text.title.family": "--ds-text-title-family",
  "text.title.size": "--ds-text-title-size",
  "text.title.weight": "--ds-text-title-weight",
  "text.title.leading": "--ds-text-title-leading",
  "text.title.tracking": "--ds-text-title-tracking",
  "text.title.case": "--ds-text-title-case",
  "text.heading.family": "--ds-text-heading-family",
  "text.heading.size": "--ds-text-heading-size",
  "text.heading.weight": "--ds-text-heading-weight",
  "text.heading.leading": "--ds-text-heading-leading",
  "text.heading.tracking": "--ds-text-heading-tracking",
  "text.heading.case": "--ds-text-heading-case",
  "text.display.family": "--ds-text-display-family",
  "text.display.size": "--ds-text-display-size",
  "text.display.weight": "--ds-text-display-weight",
  "text.display.leading": "--ds-text-display-leading",
  "text.display.tracking": "--ds-text-display-tracking",
  "text.display.case": "--ds-text-display-case",
  "text.numeric.family": "--ds-text-numeric-family",
  "text.numeric.size": "--ds-text-numeric-size",
  "text.numeric.weight": "--ds-text-numeric-weight",
  "text.numeric.leading": "--ds-text-numeric-leading",
  "text.numeric.tracking": "--ds-text-numeric-tracking",
  "text.numeric.case": "--ds-text-numeric-case",
  "text.readout.family": "--ds-text-readout-family",
  "text.readout.size": "--ds-text-readout-size",
  "text.readout.weight": "--ds-text-readout-weight",
  "text.readout.leading": "--ds-text-readout-leading",
  "text.readout.tracking": "--ds-text-readout-tracking",
  "text.readout.case": "--ds-text-readout-case",
  "text.code.family": "--ds-text-code-family",
  "text.code.size": "--ds-text-code-size",
  "text.code.weight": "--ds-text-code-weight",
  "text.code.leading": "--ds-text-code-leading",
  "text.code.tracking": "--ds-text-code-tracking",
  "text.code.case": "--ds-text-code-case",
  "space.0": "--ds-space-0",
  "space.1": "--ds-space-1",
  "space.2": "--ds-space-2",
  "space.3": "--ds-space-3",
  "space.4": "--ds-space-4",
  "space.5": "--ds-space-5",
  "space.6": "--ds-space-6",
  "space.8": "--ds-space-8",
  "space.10": "--ds-space-10",
  "space.12": "--ds-space-12",
  "space.16": "--ds-space-16",
  "space.hairline": "--ds-space-hairline",
  "space.half": "--ds-space-half",
  "size.control": "--ds-size-control",
  "size.control-sm": "--ds-size-control-sm",
  "size.control-padding": "--ds-size-control-padding",
  "size.target": "--ds-size-target",
  "size.icon": "--ds-size-icon",
  "size.row": "--ds-size-row",
  "size.bar": "--ds-size-bar",
  "size.focus-ring": "--ds-size-focus-ring",
  "radius.none": "--ds-radius-none",
  "radius.control": "--ds-radius-control",
  "radius.panel": "--ds-radius-panel",
  "radius.overlay": "--ds-radius-overlay",
  "radius.pill": "--ds-radius-pill",
  "motion.duration.instant": "--ds-duration-instant",
  "motion.duration.fast": "--ds-duration-fast",
  "motion.duration.base": "--ds-duration-base",
  "motion.duration.slow": "--ds-duration-slow",
  "motion.easing.standard": "--ds-ease-standard",
  "motion.easing.enter": "--ds-ease-enter",
  "motion.easing.exit": "--ds-ease-exit",
  "timing.hold": "--ds-timing-hold",
  "timing.arm": "--ds-timing-arm",
  "timing.notice": "--ds-timing-notice",
  "layer.sticky": "--ds-layer-sticky",
  "layer.modal": "--ds-layer-modal",
  "layer.popover": "--ds-layer-popover",
  "layer.toast": "--ds-layer-toast",
  "layer.tooltip": "--ds-layer-tooltip",
  "color.surface.ground": "--ds-surface-ground",
  "color.surface.panel": "--ds-surface-panel",
  "color.surface.inset": "--ds-surface-inset",
  "color.surface.raised": "--ds-surface-raised",
  "color.surface.raised-hover": "--ds-surface-raised-hover",
  "color.surface.overlay": "--ds-surface-overlay",
  "color.surface.canvas": "--ds-surface-canvas",
  "color.ink.primary": "--ds-ink-primary",
  "color.ink.secondary": "--ds-ink-secondary",
  "color.ink.tertiary": "--ds-ink-tertiary",
  "color.ink.disabled": "--ds-ink-disabled",
  "color.ink.inverse": "--ds-ink-inverse",
  "color.ink.on-canvas": "--ds-ink-on-canvas",
  "color.line.subtle": "--ds-line-subtle",
  "color.line.strong": "--ds-line-strong",
  "color.line.control": "--ds-line-control",
  "color.accent.default": "--ds-accent",
  "color.accent.hover": "--ds-accent-hover",
  "color.accent.ink": "--ds-accent-ink",
  "color.accent.on": "--ds-accent-on",
  "color.accent.soft": "--ds-accent-soft",
  "color.focus": "--ds-focus",
  "color.ok.default": "--ds-ok",
  "color.ok.ink": "--ds-ok-ink",
  "color.ok.on": "--ds-ok-on",
  "color.ok.soft": "--ds-ok-soft",
  "color.warn.default": "--ds-warn",
  "color.warn.ink": "--ds-warn-ink",
  "color.warn.on": "--ds-warn-on",
  "color.warn.soft": "--ds-warn-soft",
  "color.bad.default": "--ds-bad",
  "color.bad.ink": "--ds-bad-ink",
  "color.bad.on": "--ds-bad-on",
  "color.bad.soft": "--ds-bad-soft",
  "color.wash.hover": "--ds-wash-hover",
  "color.wash.pressed": "--ds-wash-pressed",
  "color.veil": "--ds-veil",
  "elevation.menu": "--ds-elevation-menu",
  "elevation.modal": "--ds-elevation-modal",
  "text.label": "--ds-text-label",
  "text.caption": "--ds-text-caption",
  "text.body": "--ds-text-body",
  "text.control": "--ds-text-control",
  "text.prose": "--ds-text-prose",
  "text.title": "--ds-text-title",
  "text.heading": "--ds-text-heading",
  "text.display": "--ds-text-display",
  "text.numeric": "--ds-text-numeric",
  "text.readout": "--ds-text-readout",
  "text.code": "--ds-text-code"
};
