// @letissier/design-system 0.2.0 · tokens.d.ts · sha256-6db024082153427c · vendored by scripts/sync.mjs; change the design-system repo, not this copy
// GENERATED by build/build.mjs from tokens/*.tokens.json — do not edit.
// design-system 0.2.0 · change a token in tokens/, then run `npm run build`.

/** The modes of each axis; the first is the default. */
export declare const modes: {
  readonly "theme": readonly ["dark", "light"];
  readonly "density": readonly ["regular", "compact", "touch"];
  readonly "motion": readonly ["full", "reduced"];
};

/** Raw palette, by CIELAB lightness. Prefer the roles in `color`. */
export declare const palette: {
  readonly "neutral": {
    readonly "0": "#000000";
    readonly "5": "#101012";
    readonly "6": "#141415";
    readonly "10": "#1c1c1e";
    readonly "13": "#212124";
    readonly "17": "#2a2a2e";
    readonly "19": "#2e2e33";
    readonly "21": "#323238";
    readonly "26": "#3c3c44";
    readonly "32": "#4a4a52";
    readonly "39": "#5c5c66";
    readonly "46": "#6d6c76";
    readonly "59": "#8c8c96";
    readonly "71": "#adadb7";
    readonly "79": "#c4c4cc";
    readonly "84": "#d2d2d8";
    readonly "86": "#d6d6dc";
    readonly "90": "#e2e2e7";
    readonly "94": "#ececef";
    readonly "97": "#f5f5f7";
    readonly "99": "#fbfbfc";
    readonly "100": "#ffffff";
  };
  readonly "cyan": {
    readonly "36": "#015b7e";
    readonly "42": "#036a91";
    readonly "74": "#39c2ff";
    readonly "80": "#78d1ff";
  };
  readonly "amber": {
    readonly "39": "#805200";
    readonly "40": "#835503";
    readonly "56": "#b8790b";
    readonly "78": "#ffb347";
  };
  readonly "red": {
    readonly "39": "#bb011e";
    readonly "40": "#be0920";
    readonly "59": "#ff4d4d";
    readonly "64": "#fe6c67";
  };
  readonly "green": {
    readonly "39": "#006a38";
    readonly "40": "#026d3a";
    readonly "76": "#33d67e";
  };
  readonly "alpha": {
    readonly "white-6": "#ffffff0f";
    readonly "white-10": "#ffffff1a";
    readonly "white-16": "#ffffff29";
    readonly "black-6": "#0000000f";
    readonly "black-10": "#0000001a";
    readonly "black-16": "#00000029";
    readonly "black-20": "#00000033";
    readonly "black-30": "#0000004d";
    readonly "black-40": "#00000066";
    readonly "black-45": "#00000073";
    readonly "black-55": "#0000008c";
    readonly "cyan-74-16": "#39c2ff29";
    readonly "cyan-42-10": "#036a911a";
    readonly "amber-78-14": "#ffb34724";
    readonly "amber-56-16": "#b8790b29";
    readonly "red-59-14": "#ff4d4d24";
    readonly "red-40-10": "#be09201a";
    readonly "green-76-12": "#33d67e1f";
    readonly "green-40-10": "#026d3a1a";
  };
};

/** Colour roles per theme, resolved to hex. */
export declare const color: {
  readonly "dark": {
    readonly "surface": {
      readonly "ground": "#141415";
      readonly "panel": "#1c1c1e";
      readonly "inset": "#212124";
      readonly "raised": "#2a2a2e";
      readonly "raised-hover": "#323238";
      readonly "overlay": "#212124";
      readonly "canvas": "#101012";
    };
    readonly "ink": {
      readonly "primary": "#d2d2d8";
      readonly "secondary": "#adadb7";
      readonly "tertiary": "#8c8c96";
      readonly "disabled": "#5c5c66";
      readonly "inverse": "#141415";
      readonly "on-canvas": "#d2d2d8";
    };
    readonly "line": {
      readonly "subtle": "#2e2e33";
      readonly "strong": "#3c3c44";
      readonly "control": "#6d6c76";
    };
    readonly "accent": {
      readonly "default": "#39c2ff";
      readonly "hover": "#78d1ff";
      readonly "ink": "#39c2ff";
      readonly "on": "#101012";
      readonly "soft": "#39c2ff29";
    };
    readonly "focus": "#39c2ff";
    readonly "ok": {
      readonly "default": "#33d67e";
      readonly "ink": "#33d67e";
      readonly "on": "#101012";
      readonly "soft": "#33d67e1f";
    };
    readonly "warn": {
      readonly "default": "#ffb347";
      readonly "ink": "#ffb347";
      readonly "on": "#101012";
      readonly "soft": "#ffb34724";
    };
    readonly "bad": {
      readonly "default": "#ff4d4d";
      readonly "ink": "#fe6c67";
      readonly "on": "#101012";
      readonly "soft": "#ff4d4d24";
    };
    readonly "wash": {
      readonly "hover": "#ffffff0f";
      readonly "pressed": "#ffffff1a";
      readonly "dragged": "#ffffff29";
    };
    readonly "veil": "#0000008c";
  };
  readonly "light": {
    readonly "surface": {
      readonly "ground": "#ececef";
      readonly "panel": "#f5f5f7";
      readonly "inset": "#e2e2e7";
      readonly "raised": "#fbfbfc";
      readonly "raised-hover": "#d6d6dc";
      readonly "overlay": "#ffffff";
      readonly "canvas": "#101012";
    };
    readonly "ink": {
      readonly "primary": "#1c1c1e";
      readonly "secondary": "#3c3c44";
      readonly "tertiary": "#5c5c66";
      readonly "disabled": "#8c8c96";
      readonly "inverse": "#f5f5f7";
      readonly "on-canvas": "#d2d2d8";
    };
    readonly "line": {
      readonly "subtle": "#c4c4cc";
      readonly "strong": "#8c8c96";
      readonly "control": "#6d6c76";
    };
    readonly "accent": {
      readonly "default": "#036a91";
      readonly "hover": "#015b7e";
      readonly "ink": "#015b7e";
      readonly "on": "#ffffff";
      readonly "soft": "#036a911a";
    };
    readonly "focus": "#036a91";
    readonly "ok": {
      readonly "default": "#026d3a";
      readonly "ink": "#006a38";
      readonly "on": "#ffffff";
      readonly "soft": "#026d3a1a";
    };
    readonly "warn": {
      readonly "default": "#b8790b";
      readonly "ink": "#805200";
      readonly "on": "#101012";
      readonly "soft": "#b8790b29";
    };
    readonly "bad": {
      readonly "default": "#be0920";
      readonly "ink": "#bb011e";
      readonly "on": "#ffffff";
      readonly "soft": "#be09201a";
    };
    readonly "wash": {
      readonly "hover": "#0000000f";
      readonly "pressed": "#0000001a";
      readonly "dragged": "#00000029";
    };
    readonly "veil": "#00000066";
  };
};

/** Box shadows per theme, as CSS. */
export declare const elevation: {
  readonly "dark": {
    readonly "menu": "0px 8px 24px 0px #00000073";
    readonly "modal": "0px 18px 50px 0px #0000008c";
  };
  readonly "light": {
    readonly "menu": "0px 8px 24px 0px #00000033";
    readonly "modal": "0px 18px 50px 0px #0000004d";
  };
};

/** Font families (as lists and as CSS stacks) and weights. */
export declare const font: {
  readonly "family": {
    readonly "sans": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
    readonly "mono": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
    readonly "display": readonly ["Archivo", "IBM Plex Sans", "system-ui", "sans-serif"];
  };
  readonly "stack": {
    readonly "sans": "'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
    readonly "mono": "'IBM Plex Mono', ui-monospace, 'SF Mono', SFMono-Regular, Menlo, Consolas, monospace";
    readonly "display": "Archivo, 'IBM Plex Sans', system-ui, sans-serif";
  };
  readonly "weight": {
    readonly "regular": 400;
    readonly "medium": 500;
    readonly "semibold": 600;
    readonly "bold": 700;
  };
};

/** Text styles per density: size in px, leading as a multiple, tracking in em. */
export declare const text: {
  readonly "regular": {
    readonly "label": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 11;
      readonly "weight": 500;
      readonly "leading": 1.2;
      readonly "tracking": "0.08em";
      readonly "case": "uppercase";
    };
    readonly "caption": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 12;
      readonly "weight": 400;
      readonly "leading": 1.35;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "body": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 13;
      readonly "weight": 400;
      readonly "leading": 1.45;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "control": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 13;
      readonly "weight": 500;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "prose": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 14;
      readonly "weight": 400;
      readonly "leading": 1.55;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "title": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 15;
      readonly "weight": 600;
      readonly "leading": 1.3;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "heading": {
      readonly "family": readonly ["Archivo", "IBM Plex Sans", "system-ui", "sans-serif"];
      readonly "size": 20;
      readonly "weight": 600;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "display": {
      readonly "family": readonly ["Archivo", "IBM Plex Sans", "system-ui", "sans-serif"];
      readonly "size": 32;
      readonly "weight": 700;
      readonly "leading": 1.1;
      readonly "tracking": "-0.01em";
      readonly "case": "none";
    };
    readonly "numeric": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 13;
      readonly "weight": 400;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "readout": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 22;
      readonly "weight": 500;
      readonly "leading": 1;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "code": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 13;
      readonly "weight": 400;
      readonly "leading": 1.5;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
  };
  readonly "compact": {
    readonly "label": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 11;
      readonly "weight": 500;
      readonly "leading": 1.2;
      readonly "tracking": "0.08em";
      readonly "case": "uppercase";
    };
    readonly "caption": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 11;
      readonly "weight": 400;
      readonly "leading": 1.35;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "body": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 12;
      readonly "weight": 400;
      readonly "leading": 1.45;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "control": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 12;
      readonly "weight": 500;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "prose": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 12;
      readonly "weight": 400;
      readonly "leading": 1.55;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "title": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 13;
      readonly "weight": 600;
      readonly "leading": 1.3;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "heading": {
      readonly "family": readonly ["Archivo", "IBM Plex Sans", "system-ui", "sans-serif"];
      readonly "size": 18;
      readonly "weight": 600;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "display": {
      readonly "family": readonly ["Archivo", "IBM Plex Sans", "system-ui", "sans-serif"];
      readonly "size": 28;
      readonly "weight": 700;
      readonly "leading": 1.1;
      readonly "tracking": "-0.01em";
      readonly "case": "none";
    };
    readonly "numeric": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 12;
      readonly "weight": 400;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "readout": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 22;
      readonly "weight": 500;
      readonly "leading": 1;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "code": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 12;
      readonly "weight": 400;
      readonly "leading": 1.5;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
  };
  readonly "touch": {
    readonly "label": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 12;
      readonly "weight": 500;
      readonly "leading": 1.2;
      readonly "tracking": "0.08em";
      readonly "case": "uppercase";
    };
    readonly "caption": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 13;
      readonly "weight": 400;
      readonly "leading": 1.35;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "body": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 15;
      readonly "weight": 400;
      readonly "leading": 1.45;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "control": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 15;
      readonly "weight": 500;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "prose": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 16;
      readonly "weight": 400;
      readonly "leading": 1.55;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "title": {
      readonly "family": readonly ["IBM Plex Sans", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"];
      readonly "size": 17;
      readonly "weight": 600;
      readonly "leading": 1.3;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "heading": {
      readonly "family": readonly ["Archivo", "IBM Plex Sans", "system-ui", "sans-serif"];
      readonly "size": 24;
      readonly "weight": 600;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "display": {
      readonly "family": readonly ["Archivo", "IBM Plex Sans", "system-ui", "sans-serif"];
      readonly "size": 40;
      readonly "weight": 700;
      readonly "leading": 1.1;
      readonly "tracking": "-0.01em";
      readonly "case": "none";
    };
    readonly "numeric": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 15;
      readonly "weight": 400;
      readonly "leading": 1.2;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "readout": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 28;
      readonly "weight": 500;
      readonly "leading": 1;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
    readonly "code": {
      readonly "family": readonly ["IBM Plex Mono", "ui-monospace", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"];
      readonly "size": 14;
      readonly "weight": 400;
      readonly "leading": 1.5;
      readonly "tracking": "0em";
      readonly "case": "none";
    };
  };
};

/** The 4px spacing grid, in px. */
export declare const space: {
  readonly "0": 0;
  readonly "1": 4;
  readonly "2": 8;
  readonly "3": 12;
  readonly "4": 16;
  readonly "5": 20;
  readonly "6": 24;
  readonly "8": 32;
  readonly "10": 40;
  readonly "12": 48;
  readonly "16": 64;
  readonly "hairline": 1;
  readonly "half": 2;
};

/** Control geometry per density, in px. */
export declare const size: {
  readonly "regular": {
    readonly "control": 32;
    readonly "control-sm": 24;
    readonly "control-padding": 12;
    readonly "target": 24;
    readonly "icon": 16;
    readonly "row": 32;
    readonly "bar": 48;
    readonly "rail": 72;
    readonly "rail-expanded": 224;
    readonly "navbar": 56;
    readonly "crumb": 200;
    readonly "focus-ring": 2;
  };
  readonly "compact": {
    readonly "control": 26;
    readonly "control-sm": 20;
    readonly "control-padding": 8;
    readonly "target": 24;
    readonly "icon": 14;
    readonly "row": 24;
    readonly "bar": 40;
    readonly "rail": 56;
    readonly "rail-expanded": 200;
    readonly "navbar": 48;
    readonly "crumb": 160;
    readonly "focus-ring": 2;
  };
  readonly "touch": {
    readonly "control": 44;
    readonly "control-sm": 32;
    readonly "control-padding": 16;
    readonly "target": 44;
    readonly "icon": 20;
    readonly "row": 44;
    readonly "bar": 56;
    readonly "rail": 80;
    readonly "rail-expanded": 280;
    readonly "navbar": 64;
    readonly "crumb": 160;
    readonly "focus-ring": 2;
  };
};

/** Corner radii per density, in px. */
export declare const radius: {
  readonly "regular": {
    readonly "none": 0;
    readonly "control": 4;
    readonly "panel": 6;
    readonly "overlay": 8;
    readonly "pill": 999;
  };
  readonly "compact": {
    readonly "none": 0;
    readonly "control": 3;
    readonly "panel": 4;
    readonly "overlay": 6;
    readonly "pill": 999;
  };
  readonly "touch": {
    readonly "none": 0;
    readonly "control": 6;
    readonly "panel": 8;
    readonly "overlay": 12;
    readonly "pill": 999;
  };
};

/** Transition durations in ms, at full motion. Code that animates reads `motion.reduced` instead when the user asks for less motion. */
export declare const duration: {
  readonly "instant": 70;
  readonly "fast": 120;
  readonly "base": 160;
  readonly "slow": 240;
};

/** Cubic-bézier control points. */
export declare const easing: {
  readonly "standard": readonly [0.2, 0, 0, 1];
  readonly "enter": readonly [0, 0, 0.2, 1];
  readonly "exit": readonly [0.4, 0, 1, 1];
  readonly "emphasized-enter": readonly [0.05, 0.7, 0.1, 1];
  readonly "emphasized-exit": readonly [0.3, 0, 0.8, 0.15];
  readonly "linear": readonly [0, 0, 1, 1];
};

/** Everything motion, per mode: durations and loops in ms, easings, offsets in px, scale. `reduced` keeps fades and removes movement. */
export declare const motion: {
  readonly "full": {
    readonly "duration": {
      readonly "instant": 70;
      readonly "fast": 120;
      readonly "base": 160;
      readonly "slow": 240;
    };
    readonly "easing": {
      readonly "standard": readonly [0.2, 0, 0, 1];
      readonly "enter": readonly [0, 0, 0.2, 1];
      readonly "exit": readonly [0.4, 0, 1, 1];
      readonly "emphasized-enter": readonly [0.05, 0.7, 0.1, 1];
      readonly "emphasized-exit": readonly [0.3, 0, 0.8, 0.15];
      readonly "linear": readonly [0, 0, 1, 1];
    };
    readonly "offset": {
      readonly "small": 4;
      readonly "medium": 8;
      readonly "large": 24;
    };
    readonly "scale": {
      readonly "enter": 0.96;
    };
    readonly "travel": 1;
    readonly "cycle": {
      readonly "spin": 900;
      readonly "sweep": 1400;
      readonly "pulse": 1600;
    };
  };
  readonly "reduced": {
    readonly "duration": {
      readonly "instant": 70;
      readonly "fast": 120;
      readonly "base": 120;
      readonly "slow": 120;
    };
    readonly "easing": {
      readonly "standard": readonly [0.2, 0, 0, 1];
      readonly "enter": readonly [0, 0, 0.2, 1];
      readonly "exit": readonly [0.4, 0, 1, 1];
      readonly "emphasized-enter": readonly [0.05, 0.7, 0.1, 1];
      readonly "emphasized-exit": readonly [0.3, 0, 0.8, 0.15];
      readonly "linear": readonly [0, 0, 1, 1];
    };
    readonly "offset": {
      readonly "small": 0;
      readonly "medium": 0;
      readonly "large": 0;
    };
    readonly "scale": {
      readonly "enter": 1;
    };
    readonly "travel": 0;
    readonly "cycle": {
      readonly "spin": 900;
      readonly "sweep": 1400;
      readonly "pulse": 1600;
    };
  };
};

/** Behavioural timers in ms: long-press, the armed window, a notice. */
export declare const timing: {
  readonly "hold": 500;
  readonly "arm": 3000;
  readonly "notice": 4000;
  readonly "tooltip": 500;
};

/** z-index values. */
export declare const layer: {
  readonly "sticky": 10;
  readonly "modal": 200;
  readonly "popover": 300;
  readonly "toast": 400;
  readonly "tooltip": 500;
};

/** Token id → CSS custom property name. */
export declare const cssVar: {
  readonly "palette.neutral.0": "--ds-neutral-0";
  readonly "palette.neutral.5": "--ds-neutral-5";
  readonly "palette.neutral.6": "--ds-neutral-6";
  readonly "palette.neutral.10": "--ds-neutral-10";
  readonly "palette.neutral.13": "--ds-neutral-13";
  readonly "palette.neutral.17": "--ds-neutral-17";
  readonly "palette.neutral.19": "--ds-neutral-19";
  readonly "palette.neutral.21": "--ds-neutral-21";
  readonly "palette.neutral.26": "--ds-neutral-26";
  readonly "palette.neutral.32": "--ds-neutral-32";
  readonly "palette.neutral.39": "--ds-neutral-39";
  readonly "palette.neutral.46": "--ds-neutral-46";
  readonly "palette.neutral.59": "--ds-neutral-59";
  readonly "palette.neutral.71": "--ds-neutral-71";
  readonly "palette.neutral.79": "--ds-neutral-79";
  readonly "palette.neutral.84": "--ds-neutral-84";
  readonly "palette.neutral.86": "--ds-neutral-86";
  readonly "palette.neutral.90": "--ds-neutral-90";
  readonly "palette.neutral.94": "--ds-neutral-94";
  readonly "palette.neutral.97": "--ds-neutral-97";
  readonly "palette.neutral.99": "--ds-neutral-99";
  readonly "palette.neutral.100": "--ds-neutral-100";
  readonly "palette.cyan.36": "--ds-cyan-36";
  readonly "palette.cyan.42": "--ds-cyan-42";
  readonly "palette.cyan.74": "--ds-cyan-74";
  readonly "palette.cyan.80": "--ds-cyan-80";
  readonly "palette.amber.39": "--ds-amber-39";
  readonly "palette.amber.40": "--ds-amber-40";
  readonly "palette.amber.56": "--ds-amber-56";
  readonly "palette.amber.78": "--ds-amber-78";
  readonly "palette.red.39": "--ds-red-39";
  readonly "palette.red.40": "--ds-red-40";
  readonly "palette.red.59": "--ds-red-59";
  readonly "palette.red.64": "--ds-red-64";
  readonly "palette.green.39": "--ds-green-39";
  readonly "palette.green.40": "--ds-green-40";
  readonly "palette.green.76": "--ds-green-76";
  readonly "palette.alpha.white-6": "--ds-alpha-white-6";
  readonly "palette.alpha.white-10": "--ds-alpha-white-10";
  readonly "palette.alpha.white-16": "--ds-alpha-white-16";
  readonly "palette.alpha.black-6": "--ds-alpha-black-6";
  readonly "palette.alpha.black-10": "--ds-alpha-black-10";
  readonly "palette.alpha.black-16": "--ds-alpha-black-16";
  readonly "palette.alpha.black-20": "--ds-alpha-black-20";
  readonly "palette.alpha.black-30": "--ds-alpha-black-30";
  readonly "palette.alpha.black-40": "--ds-alpha-black-40";
  readonly "palette.alpha.black-45": "--ds-alpha-black-45";
  readonly "palette.alpha.black-55": "--ds-alpha-black-55";
  readonly "palette.alpha.cyan-74-16": "--ds-alpha-cyan-74-16";
  readonly "palette.alpha.cyan-42-10": "--ds-alpha-cyan-42-10";
  readonly "palette.alpha.amber-78-14": "--ds-alpha-amber-78-14";
  readonly "palette.alpha.amber-56-16": "--ds-alpha-amber-56-16";
  readonly "palette.alpha.red-59-14": "--ds-alpha-red-59-14";
  readonly "palette.alpha.red-40-10": "--ds-alpha-red-40-10";
  readonly "palette.alpha.green-76-12": "--ds-alpha-green-76-12";
  readonly "palette.alpha.green-40-10": "--ds-alpha-green-40-10";
  readonly "font.family.sans": "--ds-font-sans";
  readonly "font.family.mono": "--ds-font-mono";
  readonly "font.family.display": "--ds-font-display";
  readonly "font.weight.regular": "--ds-weight-regular";
  readonly "font.weight.medium": "--ds-weight-medium";
  readonly "font.weight.semibold": "--ds-weight-semibold";
  readonly "font.weight.bold": "--ds-weight-bold";
  readonly "text.label.family": "--ds-text-label-family";
  readonly "text.label.size": "--ds-text-label-size";
  readonly "text.label.weight": "--ds-text-label-weight";
  readonly "text.label.leading": "--ds-text-label-leading";
  readonly "text.label.tracking": "--ds-text-label-tracking";
  readonly "text.label.case": "--ds-text-label-case";
  readonly "text.caption.family": "--ds-text-caption-family";
  readonly "text.caption.size": "--ds-text-caption-size";
  readonly "text.caption.weight": "--ds-text-caption-weight";
  readonly "text.caption.leading": "--ds-text-caption-leading";
  readonly "text.caption.tracking": "--ds-text-caption-tracking";
  readonly "text.caption.case": "--ds-text-caption-case";
  readonly "text.body.family": "--ds-text-body-family";
  readonly "text.body.size": "--ds-text-body-size";
  readonly "text.body.weight": "--ds-text-body-weight";
  readonly "text.body.leading": "--ds-text-body-leading";
  readonly "text.body.tracking": "--ds-text-body-tracking";
  readonly "text.body.case": "--ds-text-body-case";
  readonly "text.control.family": "--ds-text-control-family";
  readonly "text.control.size": "--ds-text-control-size";
  readonly "text.control.weight": "--ds-text-control-weight";
  readonly "text.control.leading": "--ds-text-control-leading";
  readonly "text.control.tracking": "--ds-text-control-tracking";
  readonly "text.control.case": "--ds-text-control-case";
  readonly "text.prose.family": "--ds-text-prose-family";
  readonly "text.prose.size": "--ds-text-prose-size";
  readonly "text.prose.weight": "--ds-text-prose-weight";
  readonly "text.prose.leading": "--ds-text-prose-leading";
  readonly "text.prose.tracking": "--ds-text-prose-tracking";
  readonly "text.prose.case": "--ds-text-prose-case";
  readonly "text.title.family": "--ds-text-title-family";
  readonly "text.title.size": "--ds-text-title-size";
  readonly "text.title.weight": "--ds-text-title-weight";
  readonly "text.title.leading": "--ds-text-title-leading";
  readonly "text.title.tracking": "--ds-text-title-tracking";
  readonly "text.title.case": "--ds-text-title-case";
  readonly "text.heading.family": "--ds-text-heading-family";
  readonly "text.heading.size": "--ds-text-heading-size";
  readonly "text.heading.weight": "--ds-text-heading-weight";
  readonly "text.heading.leading": "--ds-text-heading-leading";
  readonly "text.heading.tracking": "--ds-text-heading-tracking";
  readonly "text.heading.case": "--ds-text-heading-case";
  readonly "text.display.family": "--ds-text-display-family";
  readonly "text.display.size": "--ds-text-display-size";
  readonly "text.display.weight": "--ds-text-display-weight";
  readonly "text.display.leading": "--ds-text-display-leading";
  readonly "text.display.tracking": "--ds-text-display-tracking";
  readonly "text.display.case": "--ds-text-display-case";
  readonly "text.numeric.family": "--ds-text-numeric-family";
  readonly "text.numeric.size": "--ds-text-numeric-size";
  readonly "text.numeric.weight": "--ds-text-numeric-weight";
  readonly "text.numeric.leading": "--ds-text-numeric-leading";
  readonly "text.numeric.tracking": "--ds-text-numeric-tracking";
  readonly "text.numeric.case": "--ds-text-numeric-case";
  readonly "text.readout.family": "--ds-text-readout-family";
  readonly "text.readout.size": "--ds-text-readout-size";
  readonly "text.readout.weight": "--ds-text-readout-weight";
  readonly "text.readout.leading": "--ds-text-readout-leading";
  readonly "text.readout.tracking": "--ds-text-readout-tracking";
  readonly "text.readout.case": "--ds-text-readout-case";
  readonly "text.code.family": "--ds-text-code-family";
  readonly "text.code.size": "--ds-text-code-size";
  readonly "text.code.weight": "--ds-text-code-weight";
  readonly "text.code.leading": "--ds-text-code-leading";
  readonly "text.code.tracking": "--ds-text-code-tracking";
  readonly "text.code.case": "--ds-text-code-case";
  readonly "space.0": "--ds-space-0";
  readonly "space.1": "--ds-space-1";
  readonly "space.2": "--ds-space-2";
  readonly "space.3": "--ds-space-3";
  readonly "space.4": "--ds-space-4";
  readonly "space.5": "--ds-space-5";
  readonly "space.6": "--ds-space-6";
  readonly "space.8": "--ds-space-8";
  readonly "space.10": "--ds-space-10";
  readonly "space.12": "--ds-space-12";
  readonly "space.16": "--ds-space-16";
  readonly "space.hairline": "--ds-space-hairline";
  readonly "space.half": "--ds-space-half";
  readonly "size.control": "--ds-size-control";
  readonly "size.control-sm": "--ds-size-control-sm";
  readonly "size.control-padding": "--ds-size-control-padding";
  readonly "size.target": "--ds-size-target";
  readonly "size.icon": "--ds-size-icon";
  readonly "size.row": "--ds-size-row";
  readonly "size.bar": "--ds-size-bar";
  readonly "size.rail": "--ds-size-rail";
  readonly "size.rail-expanded": "--ds-size-rail-expanded";
  readonly "size.navbar": "--ds-size-navbar";
  readonly "size.crumb": "--ds-size-crumb";
  readonly "size.focus-ring": "--ds-size-focus-ring";
  readonly "radius.none": "--ds-radius-none";
  readonly "radius.control": "--ds-radius-control";
  readonly "radius.panel": "--ds-radius-panel";
  readonly "radius.overlay": "--ds-radius-overlay";
  readonly "radius.pill": "--ds-radius-pill";
  readonly "motion.duration.instant": "--ds-duration-instant";
  readonly "motion.duration.fast": "--ds-duration-fast";
  readonly "motion.duration.base": "--ds-duration-base";
  readonly "motion.duration.slow": "--ds-duration-slow";
  readonly "motion.easing.standard": "--ds-ease-standard";
  readonly "motion.easing.enter": "--ds-ease-enter";
  readonly "motion.easing.exit": "--ds-ease-exit";
  readonly "motion.easing.emphasized-enter": "--ds-ease-emphasized-enter";
  readonly "motion.easing.emphasized-exit": "--ds-ease-emphasized-exit";
  readonly "motion.easing.linear": "--ds-ease-linear";
  readonly "motion.offset.small": "--ds-motion-offset-small";
  readonly "motion.offset.medium": "--ds-motion-offset-medium";
  readonly "motion.offset.large": "--ds-motion-offset-large";
  readonly "motion.scale.enter": "--ds-motion-scale-enter";
  readonly "motion.travel": "--ds-motion-travel";
  readonly "motion.cycle.spin": "--ds-motion-cycle-spin";
  readonly "motion.cycle.sweep": "--ds-motion-cycle-sweep";
  readonly "motion.cycle.pulse": "--ds-motion-cycle-pulse";
  readonly "timing.hold": "--ds-timing-hold";
  readonly "timing.arm": "--ds-timing-arm";
  readonly "timing.notice": "--ds-timing-notice";
  readonly "timing.tooltip": "--ds-timing-tooltip";
  readonly "layer.sticky": "--ds-layer-sticky";
  readonly "layer.modal": "--ds-layer-modal";
  readonly "layer.popover": "--ds-layer-popover";
  readonly "layer.toast": "--ds-layer-toast";
  readonly "layer.tooltip": "--ds-layer-tooltip";
  readonly "color.surface.ground": "--ds-surface-ground";
  readonly "color.surface.panel": "--ds-surface-panel";
  readonly "color.surface.inset": "--ds-surface-inset";
  readonly "color.surface.raised": "--ds-surface-raised";
  readonly "color.surface.raised-hover": "--ds-surface-raised-hover";
  readonly "color.surface.overlay": "--ds-surface-overlay";
  readonly "color.surface.canvas": "--ds-surface-canvas";
  readonly "color.ink.primary": "--ds-ink-primary";
  readonly "color.ink.secondary": "--ds-ink-secondary";
  readonly "color.ink.tertiary": "--ds-ink-tertiary";
  readonly "color.ink.disabled": "--ds-ink-disabled";
  readonly "color.ink.inverse": "--ds-ink-inverse";
  readonly "color.ink.on-canvas": "--ds-ink-on-canvas";
  readonly "color.line.subtle": "--ds-line-subtle";
  readonly "color.line.strong": "--ds-line-strong";
  readonly "color.line.control": "--ds-line-control";
  readonly "color.accent.default": "--ds-accent";
  readonly "color.accent.hover": "--ds-accent-hover";
  readonly "color.accent.ink": "--ds-accent-ink";
  readonly "color.accent.on": "--ds-accent-on";
  readonly "color.accent.soft": "--ds-accent-soft";
  readonly "color.focus": "--ds-focus";
  readonly "color.ok.default": "--ds-ok";
  readonly "color.ok.ink": "--ds-ok-ink";
  readonly "color.ok.on": "--ds-ok-on";
  readonly "color.ok.soft": "--ds-ok-soft";
  readonly "color.warn.default": "--ds-warn";
  readonly "color.warn.ink": "--ds-warn-ink";
  readonly "color.warn.on": "--ds-warn-on";
  readonly "color.warn.soft": "--ds-warn-soft";
  readonly "color.bad.default": "--ds-bad";
  readonly "color.bad.ink": "--ds-bad-ink";
  readonly "color.bad.on": "--ds-bad-on";
  readonly "color.bad.soft": "--ds-bad-soft";
  readonly "color.wash.hover": "--ds-wash-hover";
  readonly "color.wash.pressed": "--ds-wash-pressed";
  readonly "color.wash.dragged": "--ds-wash-dragged";
  readonly "color.veil": "--ds-veil";
  readonly "elevation.menu": "--ds-elevation-menu";
  readonly "elevation.modal": "--ds-elevation-modal";
  readonly "text.label": "--ds-text-label";
  readonly "text.caption": "--ds-text-caption";
  readonly "text.body": "--ds-text-body";
  readonly "text.control": "--ds-text-control";
  readonly "text.prose": "--ds-text-prose";
  readonly "text.title": "--ds-text-title";
  readonly "text.heading": "--ds-text-heading";
  readonly "text.display": "--ds-text-display";
  readonly "text.numeric": "--ds-text-numeric";
  readonly "text.readout": "--ds-text-readout";
  readonly "text.code": "--ds-text-code";
};

export type Theme = (typeof modes)["theme"][number];
export type Density = (typeof modes)["density"][number];
